services:
  - name: ats_v2_db_backup #ここを修正：　適当に命名
    type: cron
    schedule: "0 3 * * *"
    region: singapore #ここを修正：　該当DBのレギオン
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        sync: false # External DATABASE_URLをBlueprint作成時に入力。
      #   fromDatabase:
      #     name: ats_v2_db_dev # ここを修正：　該当データベースの名前-> Internal DATABASE_URLだとpd_dumpでエラーが出てしまう。
      #     property: connectionString

      # pick the region closest to your database
      # For example, us-west-2 for the Oregon region
      - key: AWS_REGION
        sync: false 
      # A globally unique name for your bucket
      # For example, <your-username>-<database name>-render-postgres-backups
      - key: S3_BUCKET_NAME
        sync: false
      # Looks like "AKIAXXXXXXXXXXXXXXXX"
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      # Postgres version of your Postgres instance 
      # For example, 14
      - key: POSTGRES_VERSION
        sync: false
